/**
 * Tator REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TatorJs);
  }
}(this, function(expect, TatorJs) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TatorJs.TatorApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('TatorApi', function() {
    describe('algorithmLaunch', function() {
      it('should call algorithmLaunch successfully', function(done) {
        //uncomment below and update the code to test algorithmLaunch
        //instance.algorithmLaunch(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('cloneMediaList', function() {
      it('should call cloneMediaList successfully', function(done) {
        //uncomment below and update the code to test cloneMediaList
        //instance.cloneMediaList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createAnalysis', function() {
      it('should call createAnalysis successfully', function(done) {
        //uncomment below and update the code to test createAnalysis
        //instance.createAnalysis(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createFavorite', function() {
      it('should call createFavorite successfully', function(done) {
        //uncomment below and update the code to test createFavorite
        //instance.createFavorite(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createLeafList', function() {
      it('should call createLeafList successfully', function(done) {
        //uncomment below and update the code to test createLeafList
        //instance.createLeafList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createLeafType', function() {
      it('should call createLeafType successfully', function(done) {
        //uncomment below and update the code to test createLeafType
        //instance.createLeafType(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createLocalizationList', function() {
      it('should call createLocalizationList successfully', function(done) {
        //uncomment below and update the code to test createLocalizationList
        //instance.createLocalizationList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createLocalizationType', function() {
      it('should call createLocalizationType successfully', function(done) {
        //uncomment below and update the code to test createLocalizationType
        //instance.createLocalizationType(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createMedia', function() {
      it('should call createMedia successfully', function(done) {
        //uncomment below and update the code to test createMedia
        //instance.createMedia(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createMediaType', function() {
      it('should call createMediaType successfully', function(done) {
        //uncomment below and update the code to test createMediaType
        //instance.createMediaType(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createMembership', function() {
      it('should call createMembership successfully', function(done) {
        //uncomment below and update the code to test createMembership
        //instance.createMembership(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createObtainAuthToken', function() {
      it('should call createObtainAuthToken successfully', function(done) {
        //uncomment below and update the code to test createObtainAuthToken
        //instance.createObtainAuthToken(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createProject', function() {
      it('should call createProject successfully', function(done) {
        //uncomment below and update the code to test createProject
        //instance.createProject(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createSection', function() {
      it('should call createSection successfully', function(done) {
        //uncomment below and update the code to test createSection
        //instance.createSection(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createStateList', function() {
      it('should call createStateList successfully', function(done) {
        //uncomment below and update the code to test createStateList
        //instance.createStateList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createStateType', function() {
      it('should call createStateType successfully', function(done) {
        //uncomment below and update the code to test createStateType
        //instance.createStateType(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createTemporaryFile', function() {
      it('should call createTemporaryFile successfully', function(done) {
        //uncomment below and update the code to test createTemporaryFile
        //instance.createTemporaryFile(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createVersion', function() {
      it('should call createVersion successfully', function(done) {
        //uncomment below and update the code to test createVersion
        //instance.createVersion(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteAlgorithm', function() {
      it('should call deleteAlgorithm successfully', function(done) {
        //uncomment below and update the code to test deleteAlgorithm
        //instance.deleteAlgorithm(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteAnalysis', function() {
      it('should call deleteAnalysis successfully', function(done) {
        //uncomment below and update the code to test deleteAnalysis
        //instance.deleteAnalysis(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteFavorite', function() {
      it('should call deleteFavorite successfully', function(done) {
        //uncomment below and update the code to test deleteFavorite
        //instance.deleteFavorite(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteJob', function() {
      it('should call deleteJob successfully', function(done) {
        //uncomment below and update the code to test deleteJob
        //instance.deleteJob(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteJobList', function() {
      it('should call deleteJobList successfully', function(done) {
        //uncomment below and update the code to test deleteJobList
        //instance.deleteJobList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteLeaf', function() {
      it('should call deleteLeaf successfully', function(done) {
        //uncomment below and update the code to test deleteLeaf
        //instance.deleteLeaf(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteLeafList', function() {
      it('should call deleteLeafList successfully', function(done) {
        //uncomment below and update the code to test deleteLeafList
        //instance.deleteLeafList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteLeafType', function() {
      it('should call deleteLeafType successfully', function(done) {
        //uncomment below and update the code to test deleteLeafType
        //instance.deleteLeafType(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteLocalization', function() {
      it('should call deleteLocalization successfully', function(done) {
        //uncomment below and update the code to test deleteLocalization
        //instance.deleteLocalization(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteLocalizationList', function() {
      it('should call deleteLocalizationList successfully', function(done) {
        //uncomment below and update the code to test deleteLocalizationList
        //instance.deleteLocalizationList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteLocalizationType', function() {
      it('should call deleteLocalizationType successfully', function(done) {
        //uncomment below and update the code to test deleteLocalizationType
        //instance.deleteLocalizationType(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteMedia', function() {
      it('should call deleteMedia successfully', function(done) {
        //uncomment below and update the code to test deleteMedia
        //instance.deleteMedia(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteMediaList', function() {
      it('should call deleteMediaList successfully', function(done) {
        //uncomment below and update the code to test deleteMediaList
        //instance.deleteMediaList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteMediaType', function() {
      it('should call deleteMediaType successfully', function(done) {
        //uncomment below and update the code to test deleteMediaType
        //instance.deleteMediaType(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteMembership', function() {
      it('should call deleteMembership successfully', function(done) {
        //uncomment below and update the code to test deleteMembership
        //instance.deleteMembership(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteProject', function() {
      it('should call deleteProject successfully', function(done) {
        //uncomment below and update the code to test deleteProject
        //instance.deleteProject(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteSection', function() {
      it('should call deleteSection successfully', function(done) {
        //uncomment below and update the code to test deleteSection
        //instance.deleteSection(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteState', function() {
      it('should call deleteState successfully', function(done) {
        //uncomment below and update the code to test deleteState
        //instance.deleteState(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteStateList', function() {
      it('should call deleteStateList successfully', function(done) {
        //uncomment below and update the code to test deleteStateList
        //instance.deleteStateList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteStateType', function() {
      it('should call deleteStateType successfully', function(done) {
        //uncomment below and update the code to test deleteStateType
        //instance.deleteStateType(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteTemporaryFile', function() {
      it('should call deleteTemporaryFile successfully', function(done) {
        //uncomment below and update the code to test deleteTemporaryFile
        //instance.deleteTemporaryFile(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteTemporaryFileList', function() {
      it('should call deleteTemporaryFileList successfully', function(done) {
        //uncomment below and update the code to test deleteTemporaryFileList
        //instance.deleteTemporaryFileList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteVersion', function() {
      it('should call deleteVersion successfully', function(done) {
        //uncomment below and update the code to test deleteVersion
        //instance.deleteVersion(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAlgorithm', function() {
      it('should call getAlgorithm successfully', function(done) {
        //uncomment below and update the code to test getAlgorithm
        //instance.getAlgorithm(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAlgorithmList', function() {
      it('should call getAlgorithmList successfully', function(done) {
        //uncomment below and update the code to test getAlgorithmList
        //instance.getAlgorithmList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAnalysis', function() {
      it('should call getAnalysis successfully', function(done) {
        //uncomment below and update the code to test getAnalysis
        //instance.getAnalysis(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAnalysisList', function() {
      it('should call getAnalysisList successfully', function(done) {
        //uncomment below and update the code to test getAnalysisList
        //instance.getAnalysisList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getClip', function() {
      it('should call getClip successfully', function(done) {
        //uncomment below and update the code to test getClip
        //instance.getClip(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getFavorite', function() {
      it('should call getFavorite successfully', function(done) {
        //uncomment below and update the code to test getFavorite
        //instance.getFavorite(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getFavoriteList', function() {
      it('should call getFavoriteList successfully', function(done) {
        //uncomment below and update the code to test getFavoriteList
        //instance.getFavoriteList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getFrame', function() {
      it('should call getFrame successfully', function(done) {
        //uncomment below and update the code to test getFrame
        //instance.getFrame(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getJob', function() {
      it('should call getJob successfully', function(done) {
        //uncomment below and update the code to test getJob
        //instance.getJob(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getJobList', function() {
      it('should call getJobList successfully', function(done) {
        //uncomment below and update the code to test getJobList
        //instance.getJobList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getLeaf', function() {
      it('should call getLeaf successfully', function(done) {
        //uncomment below and update the code to test getLeaf
        //instance.getLeaf(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getLeafCount', function() {
      it('should call getLeafCount successfully', function(done) {
        //uncomment below and update the code to test getLeafCount
        //instance.getLeafCount(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getLeafList', function() {
      it('should call getLeafList successfully', function(done) {
        //uncomment below and update the code to test getLeafList
        //instance.getLeafList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getLeafType', function() {
      it('should call getLeafType successfully', function(done) {
        //uncomment below and update the code to test getLeafType
        //instance.getLeafType(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getLeafTypeList', function() {
      it('should call getLeafTypeList successfully', function(done) {
        //uncomment below and update the code to test getLeafTypeList
        //instance.getLeafTypeList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getLocalization', function() {
      it('should call getLocalization successfully', function(done) {
        //uncomment below and update the code to test getLocalization
        //instance.getLocalization(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getLocalizationCount', function() {
      it('should call getLocalizationCount successfully', function(done) {
        //uncomment below and update the code to test getLocalizationCount
        //instance.getLocalizationCount(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getLocalizationGraphic', function() {
      it('should call getLocalizationGraphic successfully', function(done) {
        //uncomment below and update the code to test getLocalizationGraphic
        //instance.getLocalizationGraphic(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getLocalizationList', function() {
      it('should call getLocalizationList successfully', function(done) {
        //uncomment below and update the code to test getLocalizationList
        //instance.getLocalizationList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getLocalizationType', function() {
      it('should call getLocalizationType successfully', function(done) {
        //uncomment below and update the code to test getLocalizationType
        //instance.getLocalizationType(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getLocalizationTypeList', function() {
      it('should call getLocalizationTypeList successfully', function(done) {
        //uncomment below and update the code to test getLocalizationTypeList
        //instance.getLocalizationTypeList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getMedia', function() {
      it('should call getMedia successfully', function(done) {
        //uncomment below and update the code to test getMedia
        //instance.getMedia(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getMediaCount', function() {
      it('should call getMediaCount successfully', function(done) {
        //uncomment below and update the code to test getMediaCount
        //instance.getMediaCount(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getMediaList', function() {
      it('should call getMediaList successfully', function(done) {
        //uncomment below and update the code to test getMediaList
        //instance.getMediaList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getMediaNext', function() {
      it('should call getMediaNext successfully', function(done) {
        //uncomment below and update the code to test getMediaNext
        //instance.getMediaNext(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getMediaPrev', function() {
      it('should call getMediaPrev successfully', function(done) {
        //uncomment below and update the code to test getMediaPrev
        //instance.getMediaPrev(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getMediaStats', function() {
      it('should call getMediaStats successfully', function(done) {
        //uncomment below and update the code to test getMediaStats
        //instance.getMediaStats(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getMediaType', function() {
      it('should call getMediaType successfully', function(done) {
        //uncomment below and update the code to test getMediaType
        //instance.getMediaType(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getMediaTypeList', function() {
      it('should call getMediaTypeList successfully', function(done) {
        //uncomment below and update the code to test getMediaTypeList
        //instance.getMediaTypeList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getMembership', function() {
      it('should call getMembership successfully', function(done) {
        //uncomment below and update the code to test getMembership
        //instance.getMembership(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getMembershipList', function() {
      it('should call getMembershipList successfully', function(done) {
        //uncomment below and update the code to test getMembershipList
        //instance.getMembershipList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getProject', function() {
      it('should call getProject successfully', function(done) {
        //uncomment below and update the code to test getProject
        //instance.getProject(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getProjectList', function() {
      it('should call getProjectList successfully', function(done) {
        //uncomment below and update the code to test getProjectList
        //instance.getProjectList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getSection', function() {
      it('should call getSection successfully', function(done) {
        //uncomment below and update the code to test getSection
        //instance.getSection(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getSectionAnalysis', function() {
      it('should call getSectionAnalysis successfully', function(done) {
        //uncomment below and update the code to test getSectionAnalysis
        //instance.getSectionAnalysis(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getSectionList', function() {
      it('should call getSectionList successfully', function(done) {
        //uncomment below and update the code to test getSectionList
        //instance.getSectionList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getState', function() {
      it('should call getState successfully', function(done) {
        //uncomment below and update the code to test getState
        //instance.getState(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getStateCount', function() {
      it('should call getStateCount successfully', function(done) {
        //uncomment below and update the code to test getStateCount
        //instance.getStateCount(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getStateGraphic', function() {
      it('should call getStateGraphic successfully', function(done) {
        //uncomment below and update the code to test getStateGraphic
        //instance.getStateGraphic(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getStateList', function() {
      it('should call getStateList successfully', function(done) {
        //uncomment below and update the code to test getStateList
        //instance.getStateList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getStateType', function() {
      it('should call getStateType successfully', function(done) {
        //uncomment below and update the code to test getStateType
        //instance.getStateType(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getStateTypeList', function() {
      it('should call getStateTypeList successfully', function(done) {
        //uncomment below and update the code to test getStateTypeList
        //instance.getStateTypeList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTemporaryFile', function() {
      it('should call getTemporaryFile successfully', function(done) {
        //uncomment below and update the code to test getTemporaryFile
        //instance.getTemporaryFile(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTemporaryFileList', function() {
      it('should call getTemporaryFileList successfully', function(done) {
        //uncomment below and update the code to test getTemporaryFileList
        //instance.getTemporaryFileList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getVersion', function() {
      it('should call getVersion successfully', function(done) {
        //uncomment below and update the code to test getVersion
        //instance.getVersion(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getVersionList', function() {
      it('should call getVersionList successfully', function(done) {
        //uncomment below and update the code to test getVersionList
        //instance.getVersionList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('leafSuggestion', function() {
      it('should call leafSuggestion successfully', function(done) {
        //uncomment below and update the code to test leafSuggestion
        //instance.leafSuggestion(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('mergeStates', function() {
      it('should call mergeStates successfully', function(done) {
        //uncomment below and update the code to test mergeStates
        //instance.mergeStates(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('moveVideo', function() {
      it('should call moveVideo successfully', function(done) {
        //uncomment below and update the code to test moveVideo
        //instance.moveVideo(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('notify', function() {
      it('should call notify successfully', function(done) {
        //uncomment below and update the code to test notify
        //instance.notify(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('registerAlgorithm', function() {
      it('should call registerAlgorithm successfully', function(done) {
        //uncomment below and update the code to test registerAlgorithm
        //instance.registerAlgorithm(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('saveAlgorithmManifest', function() {
      it('should call saveAlgorithmManifest successfully', function(done) {
        //uncomment below and update the code to test saveAlgorithmManifest
        //instance.saveAlgorithmManifest(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('transcode', function() {
      it('should call transcode successfully', function(done) {
        //uncomment below and update the code to test transcode
        //instance.transcode(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('trimStateEnd', function() {
      it('should call trimStateEnd successfully', function(done) {
        //uncomment below and update the code to test trimStateEnd
        //instance.trimStateEnd(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateAlgorithm', function() {
      it('should call updateAlgorithm successfully', function(done) {
        //uncomment below and update the code to test updateAlgorithm
        //instance.updateAlgorithm(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateAnalysis', function() {
      it('should call updateAnalysis successfully', function(done) {
        //uncomment below and update the code to test updateAnalysis
        //instance.updateAnalysis(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateFavorite', function() {
      it('should call updateFavorite successfully', function(done) {
        //uncomment below and update the code to test updateFavorite
        //instance.updateFavorite(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateLeaf', function() {
      it('should call updateLeaf successfully', function(done) {
        //uncomment below and update the code to test updateLeaf
        //instance.updateLeaf(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateLeafList', function() {
      it('should call updateLeafList successfully', function(done) {
        //uncomment below and update the code to test updateLeafList
        //instance.updateLeafList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateLeafType', function() {
      it('should call updateLeafType successfully', function(done) {
        //uncomment below and update the code to test updateLeafType
        //instance.updateLeafType(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateLocalization', function() {
      it('should call updateLocalization successfully', function(done) {
        //uncomment below and update the code to test updateLocalization
        //instance.updateLocalization(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateLocalizationList', function() {
      it('should call updateLocalizationList successfully', function(done) {
        //uncomment below and update the code to test updateLocalizationList
        //instance.updateLocalizationList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateLocalizationType', function() {
      it('should call updateLocalizationType successfully', function(done) {
        //uncomment below and update the code to test updateLocalizationType
        //instance.updateLocalizationType(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateMedia', function() {
      it('should call updateMedia successfully', function(done) {
        //uncomment below and update the code to test updateMedia
        //instance.updateMedia(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateMediaList', function() {
      it('should call updateMediaList successfully', function(done) {
        //uncomment below and update the code to test updateMediaList
        //instance.updateMediaList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateMediaType', function() {
      it('should call updateMediaType successfully', function(done) {
        //uncomment below and update the code to test updateMediaType
        //instance.updateMediaType(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateMembership', function() {
      it('should call updateMembership successfully', function(done) {
        //uncomment below and update the code to test updateMembership
        //instance.updateMembership(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateProject', function() {
      it('should call updateProject successfully', function(done) {
        //uncomment below and update the code to test updateProject
        //instance.updateProject(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateSection', function() {
      it('should call updateSection successfully', function(done) {
        //uncomment below and update the code to test updateSection
        //instance.updateSection(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateState', function() {
      it('should call updateState successfully', function(done) {
        //uncomment below and update the code to test updateState
        //instance.updateState(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateStateList', function() {
      it('should call updateStateList successfully', function(done) {
        //uncomment below and update the code to test updateStateList
        //instance.updateStateList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateStateType', function() {
      it('should call updateStateType successfully', function(done) {
        //uncomment below and update the code to test updateStateType
        //instance.updateStateType(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateVersion', function() {
      it('should call updateVersion successfully', function(done) {
        //uncomment below and update the code to test updateVersion
        //instance.updateVersion(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('whoami', function() {
      it('should call whoami successfully', function(done) {
        //uncomment below and update the code to test whoami
        //instance.whoami(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
