/**
 * Tator REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import Algorithm from './model/Algorithm';
import AlgorithmLaunch from './model/AlgorithmLaunch';
import AlgorithmLaunchSpec from './model/AlgorithmLaunchSpec';
import AlgorithmManifest from './model/AlgorithmManifest';
import AlgorithmManifestSpec from './model/AlgorithmManifestSpec';
import AlgorithmParameter from './model/AlgorithmParameter';
import AlgorithmSpec from './model/AlgorithmSpec';
import Analysis from './model/Analysis';
import AnalysisSpec from './model/AnalysisSpec';
import ArchiveConfig from './model/ArchiveConfig';
import AttributeBulkUpdate from './model/AttributeBulkUpdate';
import AttributeType from './model/AttributeType';
import AttributeValue from './model/AttributeValue';
import AudioDefinition from './model/AudioDefinition';
import AutocompleteService from './model/AutocompleteService';
import BadRequestResponse from './model/BadRequestResponse';
import CloneMediaSpec from './model/CloneMediaSpec';
import Color from './model/Color';
import ColorMap from './model/ColorMap';
import CreateListResponse from './model/CreateListResponse';
import CreateResponse from './model/CreateResponse';
import Credentials from './model/Credentials';
import EncodeConfig from './model/EncodeConfig';
import Favorite from './model/Favorite';
import FavoriteSpec from './model/FavoriteSpec';
import FavoriteUpdate from './model/FavoriteUpdate';
import Fill from './model/Fill';
import Job from './model/Job';
import JobNode from './model/JobNode';
import Leaf from './model/Leaf';
import LeafSpec from './model/LeafSpec';
import LeafSuggestion from './model/LeafSuggestion';
import LeafType from './model/LeafType';
import LeafTypeSpec from './model/LeafTypeSpec';
import LeafTypeUpdate from './model/LeafTypeUpdate';
import LeafUpdate from './model/LeafUpdate';
import Localization from './model/Localization';
import LocalizationSpec from './model/LocalizationSpec';
import LocalizationType from './model/LocalizationType';
import LocalizationTypeSpec from './model/LocalizationTypeSpec';
import LocalizationTypeUpdate from './model/LocalizationTypeUpdate';
import LocalizationUpdate from './model/LocalizationUpdate';
import Media from './model/Media';
import MediaFiles from './model/MediaFiles';
import MediaNext from './model/MediaNext';
import MediaPrev from './model/MediaPrev';
import MediaSpec from './model/MediaSpec';
import MediaStats from './model/MediaStats';
import MediaType from './model/MediaType';
import MediaTypeSpec from './model/MediaTypeSpec';
import MediaTypeUpdate from './model/MediaTypeUpdate';
import MediaUpdate from './model/MediaUpdate';
import Membership from './model/Membership';
import MembershipSpec from './model/MembershipSpec';
import MembershipUpdate from './model/MembershipUpdate';
import MessageResponse from './model/MessageResponse';
import MoveVideoSpec from './model/MoveVideoSpec';
import NotFoundResponse from './model/NotFoundResponse';
import NotifySpec from './model/NotifySpec';
import Project from './model/Project';
import ProjectSpec from './model/ProjectSpec';
import ResolutionConfig from './model/ResolutionConfig';
import S3StorageConfig from './model/S3StorageConfig';
import Section from './model/Section';
import SectionSpec from './model/SectionSpec';
import State from './model/State';
import StateMergeUpdate from './model/StateMergeUpdate';
import StateSpec from './model/StateSpec';
import StateTrimUpdate from './model/StateTrimUpdate';
import StateType from './model/StateType';
import StateTypeSpec from './model/StateTypeSpec';
import StateTypeUpdate from './model/StateTypeUpdate';
import StateUpdate from './model/StateUpdate';
import TemporaryFile from './model/TemporaryFile';
import TemporaryFileSpec from './model/TemporaryFileSpec';
import Token from './model/Token';
import Transcode from './model/Transcode';
import TranscodeSpec from './model/TranscodeSpec';
import User from './model/User';
import UserUpdate from './model/UserUpdate';
import Version from './model/Version';
import VersionSpec from './model/VersionSpec';
import VersionUpdate from './model/VersionUpdate';
import VideoClip from './model/VideoClip';
import VideoDefinition from './model/VideoDefinition';
import TatorApi from './api/TatorApi';


/**
* JS API client generated by OpenAPI Generator.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var TatorJs = require('index'); // See note below*.
* var xxxSvc = new TatorJs.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new TatorJs.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new TatorJs.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new TatorJs.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 0.0.1
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The Algorithm model constructor.
     * @property {module:model/Algorithm}
     */
    Algorithm,

    /**
     * The AlgorithmLaunch model constructor.
     * @property {module:model/AlgorithmLaunch}
     */
    AlgorithmLaunch,

    /**
     * The AlgorithmLaunchSpec model constructor.
     * @property {module:model/AlgorithmLaunchSpec}
     */
    AlgorithmLaunchSpec,

    /**
     * The AlgorithmManifest model constructor.
     * @property {module:model/AlgorithmManifest}
     */
    AlgorithmManifest,

    /**
     * The AlgorithmManifestSpec model constructor.
     * @property {module:model/AlgorithmManifestSpec}
     */
    AlgorithmManifestSpec,

    /**
     * The AlgorithmParameter model constructor.
     * @property {module:model/AlgorithmParameter}
     */
    AlgorithmParameter,

    /**
     * The AlgorithmSpec model constructor.
     * @property {module:model/AlgorithmSpec}
     */
    AlgorithmSpec,

    /**
     * The Analysis model constructor.
     * @property {module:model/Analysis}
     */
    Analysis,

    /**
     * The AnalysisSpec model constructor.
     * @property {module:model/AnalysisSpec}
     */
    AnalysisSpec,

    /**
     * The ArchiveConfig model constructor.
     * @property {module:model/ArchiveConfig}
     */
    ArchiveConfig,

    /**
     * The AttributeBulkUpdate model constructor.
     * @property {module:model/AttributeBulkUpdate}
     */
    AttributeBulkUpdate,

    /**
     * The AttributeType model constructor.
     * @property {module:model/AttributeType}
     */
    AttributeType,

    /**
     * The AttributeValue model constructor.
     * @property {module:model/AttributeValue}
     */
    AttributeValue,

    /**
     * The AudioDefinition model constructor.
     * @property {module:model/AudioDefinition}
     */
    AudioDefinition,

    /**
     * The AutocompleteService model constructor.
     * @property {module:model/AutocompleteService}
     */
    AutocompleteService,

    /**
     * The BadRequestResponse model constructor.
     * @property {module:model/BadRequestResponse}
     */
    BadRequestResponse,

    /**
     * The CloneMediaSpec model constructor.
     * @property {module:model/CloneMediaSpec}
     */
    CloneMediaSpec,

    /**
     * The Color model constructor.
     * @property {module:model/Color}
     */
    Color,

    /**
     * The ColorMap model constructor.
     * @property {module:model/ColorMap}
     */
    ColorMap,

    /**
     * The CreateListResponse model constructor.
     * @property {module:model/CreateListResponse}
     */
    CreateListResponse,

    /**
     * The CreateResponse model constructor.
     * @property {module:model/CreateResponse}
     */
    CreateResponse,

    /**
     * The Credentials model constructor.
     * @property {module:model/Credentials}
     */
    Credentials,

    /**
     * The EncodeConfig model constructor.
     * @property {module:model/EncodeConfig}
     */
    EncodeConfig,

    /**
     * The Favorite model constructor.
     * @property {module:model/Favorite}
     */
    Favorite,

    /**
     * The FavoriteSpec model constructor.
     * @property {module:model/FavoriteSpec}
     */
    FavoriteSpec,

    /**
     * The FavoriteUpdate model constructor.
     * @property {module:model/FavoriteUpdate}
     */
    FavoriteUpdate,

    /**
     * The Fill model constructor.
     * @property {module:model/Fill}
     */
    Fill,

    /**
     * The Job model constructor.
     * @property {module:model/Job}
     */
    Job,

    /**
     * The JobNode model constructor.
     * @property {module:model/JobNode}
     */
    JobNode,

    /**
     * The Leaf model constructor.
     * @property {module:model/Leaf}
     */
    Leaf,

    /**
     * The LeafSpec model constructor.
     * @property {module:model/LeafSpec}
     */
    LeafSpec,

    /**
     * The LeafSuggestion model constructor.
     * @property {module:model/LeafSuggestion}
     */
    LeafSuggestion,

    /**
     * The LeafType model constructor.
     * @property {module:model/LeafType}
     */
    LeafType,

    /**
     * The LeafTypeSpec model constructor.
     * @property {module:model/LeafTypeSpec}
     */
    LeafTypeSpec,

    /**
     * The LeafTypeUpdate model constructor.
     * @property {module:model/LeafTypeUpdate}
     */
    LeafTypeUpdate,

    /**
     * The LeafUpdate model constructor.
     * @property {module:model/LeafUpdate}
     */
    LeafUpdate,

    /**
     * The Localization model constructor.
     * @property {module:model/Localization}
     */
    Localization,

    /**
     * The LocalizationSpec model constructor.
     * @property {module:model/LocalizationSpec}
     */
    LocalizationSpec,

    /**
     * The LocalizationType model constructor.
     * @property {module:model/LocalizationType}
     */
    LocalizationType,

    /**
     * The LocalizationTypeSpec model constructor.
     * @property {module:model/LocalizationTypeSpec}
     */
    LocalizationTypeSpec,

    /**
     * The LocalizationTypeUpdate model constructor.
     * @property {module:model/LocalizationTypeUpdate}
     */
    LocalizationTypeUpdate,

    /**
     * The LocalizationUpdate model constructor.
     * @property {module:model/LocalizationUpdate}
     */
    LocalizationUpdate,

    /**
     * The Media model constructor.
     * @property {module:model/Media}
     */
    Media,

    /**
     * The MediaFiles model constructor.
     * @property {module:model/MediaFiles}
     */
    MediaFiles,

    /**
     * The MediaNext model constructor.
     * @property {module:model/MediaNext}
     */
    MediaNext,

    /**
     * The MediaPrev model constructor.
     * @property {module:model/MediaPrev}
     */
    MediaPrev,

    /**
     * The MediaSpec model constructor.
     * @property {module:model/MediaSpec}
     */
    MediaSpec,

    /**
     * The MediaStats model constructor.
     * @property {module:model/MediaStats}
     */
    MediaStats,

    /**
     * The MediaType model constructor.
     * @property {module:model/MediaType}
     */
    MediaType,

    /**
     * The MediaTypeSpec model constructor.
     * @property {module:model/MediaTypeSpec}
     */
    MediaTypeSpec,

    /**
     * The MediaTypeUpdate model constructor.
     * @property {module:model/MediaTypeUpdate}
     */
    MediaTypeUpdate,

    /**
     * The MediaUpdate model constructor.
     * @property {module:model/MediaUpdate}
     */
    MediaUpdate,

    /**
     * The Membership model constructor.
     * @property {module:model/Membership}
     */
    Membership,

    /**
     * The MembershipSpec model constructor.
     * @property {module:model/MembershipSpec}
     */
    MembershipSpec,

    /**
     * The MembershipUpdate model constructor.
     * @property {module:model/MembershipUpdate}
     */
    MembershipUpdate,

    /**
     * The MessageResponse model constructor.
     * @property {module:model/MessageResponse}
     */
    MessageResponse,

    /**
     * The MoveVideoSpec model constructor.
     * @property {module:model/MoveVideoSpec}
     */
    MoveVideoSpec,

    /**
     * The NotFoundResponse model constructor.
     * @property {module:model/NotFoundResponse}
     */
    NotFoundResponse,

    /**
     * The NotifySpec model constructor.
     * @property {module:model/NotifySpec}
     */
    NotifySpec,

    /**
     * The Project model constructor.
     * @property {module:model/Project}
     */
    Project,

    /**
     * The ProjectSpec model constructor.
     * @property {module:model/ProjectSpec}
     */
    ProjectSpec,

    /**
     * The ResolutionConfig model constructor.
     * @property {module:model/ResolutionConfig}
     */
    ResolutionConfig,

    /**
     * The S3StorageConfig model constructor.
     * @property {module:model/S3StorageConfig}
     */
    S3StorageConfig,

    /**
     * The Section model constructor.
     * @property {module:model/Section}
     */
    Section,

    /**
     * The SectionSpec model constructor.
     * @property {module:model/SectionSpec}
     */
    SectionSpec,

    /**
     * The State model constructor.
     * @property {module:model/State}
     */
    State,

    /**
     * The StateMergeUpdate model constructor.
     * @property {module:model/StateMergeUpdate}
     */
    StateMergeUpdate,

    /**
     * The StateSpec model constructor.
     * @property {module:model/StateSpec}
     */
    StateSpec,

    /**
     * The StateTrimUpdate model constructor.
     * @property {module:model/StateTrimUpdate}
     */
    StateTrimUpdate,

    /**
     * The StateType model constructor.
     * @property {module:model/StateType}
     */
    StateType,

    /**
     * The StateTypeSpec model constructor.
     * @property {module:model/StateTypeSpec}
     */
    StateTypeSpec,

    /**
     * The StateTypeUpdate model constructor.
     * @property {module:model/StateTypeUpdate}
     */
    StateTypeUpdate,

    /**
     * The StateUpdate model constructor.
     * @property {module:model/StateUpdate}
     */
    StateUpdate,

    /**
     * The TemporaryFile model constructor.
     * @property {module:model/TemporaryFile}
     */
    TemporaryFile,

    /**
     * The TemporaryFileSpec model constructor.
     * @property {module:model/TemporaryFileSpec}
     */
    TemporaryFileSpec,

    /**
     * The Token model constructor.
     * @property {module:model/Token}
     */
    Token,

    /**
     * The Transcode model constructor.
     * @property {module:model/Transcode}
     */
    Transcode,

    /**
     * The TranscodeSpec model constructor.
     * @property {module:model/TranscodeSpec}
     */
    TranscodeSpec,

    /**
     * The User model constructor.
     * @property {module:model/User}
     */
    User,

    /**
     * The UserUpdate model constructor.
     * @property {module:model/UserUpdate}
     */
    UserUpdate,

    /**
     * The Version model constructor.
     * @property {module:model/Version}
     */
    Version,

    /**
     * The VersionSpec model constructor.
     * @property {module:model/VersionSpec}
     */
    VersionSpec,

    /**
     * The VersionUpdate model constructor.
     * @property {module:model/VersionUpdate}
     */
    VersionUpdate,

    /**
     * The VideoClip model constructor.
     * @property {module:model/VideoClip}
     */
    VideoClip,

    /**
     * The VideoDefinition model constructor.
     * @property {module:model/VideoDefinition}
     */
    VideoDefinition,

    /**
    * The TatorApi service constructor.
    * @property {module:api/TatorApi}
    */
    TatorApi
};
