/**
 * Tator REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TatorJs);
  }
}(this, function(expect, TatorJs) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TatorJs.Media();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Media', function() {
    it('should create an instance of Media', function() {
      // uncomment below and update the code to test Media
      //var instane = new TatorJs.Media();
      //expect(instance).to.be.a(TatorJs.Media);
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new TatorJs.Media();
      //expect(instance).to.be();
    });

    it('should have the property mediaFiles (base name: "media_files")', function() {
      // uncomment below and update the code to test the property mediaFiles
      //var instane = new TatorJs.Media();
      //expect(instance).to.be();
    });

    it('should have the property lastEditStart (base name: "last_edit_start")', function() {
      // uncomment below and update the code to test the property lastEditStart
      //var instane = new TatorJs.Media();
      //expect(instance).to.be();
    });

    it('should have the property lastEditEnd (base name: "last_edit_end")', function() {
      // uncomment below and update the code to test the property lastEditEnd
      //var instane = new TatorJs.Media();
      //expect(instance).to.be();
    });

    it('should have the property attributes (base name: "attributes")', function() {
      // uncomment below and update the code to test the property attributes
      //var instane = new TatorJs.Media();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new TatorJs.Media();
      //expect(instance).to.be();
    });

    it('should have the property project (base name: "project")', function() {
      // uncomment below and update the code to test the property project
      //var instane = new TatorJs.Media();
      //expect(instance).to.be();
    });

    it('should have the property meta (base name: "meta")', function() {
      // uncomment below and update the code to test the property meta
      //var instane = new TatorJs.Media();
      //expect(instance).to.be();
    });

    it('should have the property file (base name: "file")', function() {
      // uncomment below and update the code to test the property file
      //var instane = new TatorJs.Media();
      //expect(instance).to.be();
    });

    it('should have the property thumbnail (base name: "thumbnail")', function() {
      // uncomment below and update the code to test the property thumbnail
      //var instane = new TatorJs.Media();
      //expect(instance).to.be();
    });

    it('should have the property thumbnailGif (base name: "thumbnail_gif")', function() {
      // uncomment below and update the code to test the property thumbnailGif
      //var instane = new TatorJs.Media();
      //expect(instance).to.be();
    });

    it('should have the property segmentInfo (base name: "segment_info")', function() {
      // uncomment below and update the code to test the property segmentInfo
      //var instane = new TatorJs.Media();
      //expect(instance).to.be();
    });

    it('should have the property createdDatetime (base name: "created_datetime")', function() {
      // uncomment below and update the code to test the property createdDatetime
      //var instane = new TatorJs.Media();
      //expect(instance).to.be();
    });

    it('should have the property createdBy (base name: "created_by")', function() {
      // uncomment below and update the code to test the property createdBy
      //var instane = new TatorJs.Media();
      //expect(instance).to.be();
    });

    it('should have the property modifiedDatetime (base name: "modified_datetime")', function() {
      // uncomment below and update the code to test the property modifiedDatetime
      //var instane = new TatorJs.Media();
      //expect(instance).to.be();
    });

    it('should have the property modifiedBy (base name: "modified_by")', function() {
      // uncomment below and update the code to test the property modifiedBy
      //var instane = new TatorJs.Media();
      //expect(instance).to.be();
    });

    it('should have the property md5 (base name: "md5")', function() {
      // uncomment below and update the code to test the property md5
      //var instane = new TatorJs.Media();
      //expect(instance).to.be();
    });

    it('should have the property numFrames (base name: "num_frames")', function() {
      // uncomment below and update the code to test the property numFrames
      //var instane = new TatorJs.Media();
      //expect(instance).to.be();
    });

    it('should have the property fps (base name: "fps")', function() {
      // uncomment below and update the code to test the property fps
      //var instane = new TatorJs.Media();
      //expect(instance).to.be();
    });

    it('should have the property codec (base name: "codec")', function() {
      // uncomment below and update the code to test the property codec
      //var instane = new TatorJs.Media();
      //expect(instance).to.be();
    });

    it('should have the property width (base name: "width")', function() {
      // uncomment below and update the code to test the property width
      //var instane = new TatorJs.Media();
      //expect(instance).to.be();
    });

    it('should have the property height (base name: "height")', function() {
      // uncomment below and update the code to test the property height
      //var instane = new TatorJs.Media();
      //expect(instance).to.be();
    });

    it('should have the property original (base name: "original")', function() {
      // uncomment below and update the code to test the property original
      //var instane = new TatorJs.Media();
      //expect(instance).to.be();
    });

    it('should have the property gid (base name: "gid")', function() {
      // uncomment below and update the code to test the property gid
      //var instane = new TatorJs.Media();
      //expect(instance).to.be();
    });

    it('should have the property uid (base name: "uid")', function() {
      // uncomment below and update the code to test the property uid
      //var instane = new TatorJs.Media();
      //expect(instance).to.be();
    });

  });

}));
