/**
 * Tator REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TatorJs);
  }
}(this, function(expect, TatorJs) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TatorJs.MediaTypeSpec();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MediaTypeSpec', function() {
    it('should create an instance of MediaTypeSpec', function() {
      // uncomment below and update the code to test MediaTypeSpec
      //var instane = new TatorJs.MediaTypeSpec();
      //expect(instance).to.be.a(TatorJs.MediaTypeSpec);
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new TatorJs.MediaTypeSpec();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instane = new TatorJs.MediaTypeSpec();
      //expect(instance).to.be();
    });

    it('should have the property dtype (base name: "dtype")', function() {
      // uncomment below and update the code to test the property dtype
      //var instane = new TatorJs.MediaTypeSpec();
      //expect(instance).to.be();
    });

    it('should have the property fileFormat (base name: "file_format")', function() {
      // uncomment below and update the code to test the property fileFormat
      //var instane = new TatorJs.MediaTypeSpec();
      //expect(instance).to.be();
    });

    it('should have the property keepOriginal (base name: "keep_original")', function() {
      // uncomment below and update the code to test the property keepOriginal
      //var instane = new TatorJs.MediaTypeSpec();
      //expect(instance).to.be();
    });

    it('should have the property defaultVolume (base name: "default_volume")', function() {
      // uncomment below and update the code to test the property defaultVolume
      //var instane = new TatorJs.MediaTypeSpec();
      //expect(instance).to.be();
    });

    it('should have the property attributeTypes (base name: "attribute_types")', function() {
      // uncomment below and update the code to test the property attributeTypes
      //var instane = new TatorJs.MediaTypeSpec();
      //expect(instance).to.be();
    });

    it('should have the property archiveConfig (base name: "archive_config")', function() {
      // uncomment below and update the code to test the property archiveConfig
      //var instane = new TatorJs.MediaTypeSpec();
      //expect(instance).to.be();
    });

    it('should have the property streamingConfig (base name: "streaming_config")', function() {
      // uncomment below and update the code to test the property streamingConfig
      //var instane = new TatorJs.MediaTypeSpec();
      //expect(instance).to.be();
    });

    it('should have the property overlayConfig (base name: "overlay_config")', function() {
      // uncomment below and update the code to test the property overlayConfig
      //var instane = new TatorJs.MediaTypeSpec();
      //expect(instance).to.be();
    });

  });

}));
