/**
 * Tator REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The LeafTypeUpdate model module.
 * @module model/LeafTypeUpdate
 * @version v1
 */
class LeafTypeUpdate {
    /**
     * Constructs a new <code>LeafTypeUpdate</code>.
     * Leaf type update.
     * @alias module:model/LeafTypeUpdate
     */
    constructor() { 
        
        LeafTypeUpdate.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>LeafTypeUpdate</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LeafTypeUpdate} obj Optional instance to populate.
     * @return {module:model/LeafTypeUpdate} The populated <code>LeafTypeUpdate</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LeafTypeUpdate();

            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Description of the leaf type.
 * @member {String} description
 * @default ''
 */
LeafTypeUpdate.prototype['description'] = '';

/**
 * Name of the leaf type.
 * @member {String} name
 */
LeafTypeUpdate.prototype['name'] = undefined;






export default LeafTypeUpdate;

