/**
 * Tator REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AudioDefinition from './AudioDefinition';
import VideoDefinition from './VideoDefinition';

/**
 * The MediaFiles model module.
 * @module model/MediaFiles
 * @version v1
 */
class MediaFiles {
    /**
     * Constructs a new <code>MediaFiles</code>.
     * Object containing upload urls for the transcoded file and corresponding &#x60;VideoDefinition&#x60;.
     * @alias module:model/MediaFiles
     */
    constructor() { 
        
        MediaFiles.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MediaFiles</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MediaFiles} obj Optional instance to populate.
     * @return {module:model/MediaFiles} The populated <code>MediaFiles</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MediaFiles();

            if (data.hasOwnProperty('archival')) {
                obj['archival'] = ApiClient.convertToType(data['archival'], [VideoDefinition]);
            }
            if (data.hasOwnProperty('streaming')) {
                obj['streaming'] = ApiClient.convertToType(data['streaming'], [VideoDefinition]);
            }
            if (data.hasOwnProperty('audio')) {
                obj['audio'] = ApiClient.convertToType(data['audio'], [AudioDefinition]);
            }
            if (data.hasOwnProperty('ids')) {
                obj['ids'] = ApiClient.convertToType(data['ids'], ['Number']);
            }
            if (data.hasOwnProperty('layout')) {
                obj['layout'] = ApiClient.convertToType(data['layout'], ['Number']);
            }
            if (data.hasOwnProperty('quality')) {
                obj['quality'] = ApiClient.convertToType(data['quality'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/VideoDefinition>} archival
 */
MediaFiles.prototype['archival'] = undefined;

/**
 * @member {Array.<module:model/VideoDefinition>} streaming
 */
MediaFiles.prototype['streaming'] = undefined;

/**
 * @member {Array.<module:model/AudioDefinition>} audio
 */
MediaFiles.prototype['audio'] = undefined;

/**
 * If multi-stream list of ids of sub-videos
 * @member {Array.<Number>} ids
 */
MediaFiles.prototype['ids'] = undefined;

/**
 * 2-element array to define rxc layout
 * @member {Array.<Number>} layout
 */
MediaFiles.prototype['layout'] = undefined;

/**
 * Resolution to fetch on each sub-video
 * @member {Number} quality
 */
MediaFiles.prototype['quality'] = undefined;






export default MediaFiles;

