/**
 * Tator REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Membership model module.
 * @module model/Membership
 * @version v1
 */
class Membership {
    /**
     * Constructs a new <code>Membership</code>.
     * Membership object.
     * @alias module:model/Membership
     */
    constructor() { 
        
        Membership.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Membership</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Membership} obj Optional instance to populate.
     * @return {module:model/Membership} The populated <code>Membership</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Membership();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('user')) {
                obj['user'] = ApiClient.convertToType(data['user'], 'Number');
            }
            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
            if (data.hasOwnProperty('permission')) {
                obj['permission'] = ApiClient.convertToType(data['permission'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Unique integer identifying a membership.
 * @member {Number} id
 */
Membership.prototype['id'] = undefined;

/**
 * Unique integer identifying a user.
 * @member {Number} user
 */
Membership.prototype['user'] = undefined;

/**
 * Username for the membership.
 * @member {String} username
 */
Membership.prototype['username'] = undefined;

/**
 * User permission level for the project.
 * @member {module:model/Membership.PermissionEnum} permission
 */
Membership.prototype['permission'] = undefined;





/**
 * Allowed values for the <code>permission</code> property.
 * @enum {String}
 * @readonly
 */
Membership['PermissionEnum'] = {

    /**
     * value: "View Only"
     * @const
     */
    "View Only": "View Only",

    /**
     * value: "Can Edit"
     * @const
     */
    "Can Edit": "Can Edit",

    /**
     * value: "Can Transfer"
     * @const
     */
    "Can Transfer": "Can Transfer",

    /**
     * value: "Can Execute"
     * @const
     */
    "Can Execute": "Can Execute",

    /**
     * value: "Full Control"
     * @const
     */
    "Full Control": "Full Control"
};



export default Membership;

