/**
 * Tator REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MembershipUpdate model module.
 * @module model/MembershipUpdate
 * @version v1
 */
class MembershipUpdate {
    /**
     * Constructs a new <code>MembershipUpdate</code>.
     * @alias module:model/MembershipUpdate
     */
    constructor() { 
        
        MembershipUpdate.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MembershipUpdate</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MembershipUpdate} obj Optional instance to populate.
     * @return {module:model/MembershipUpdate} The populated <code>MembershipUpdate</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MembershipUpdate();

            if (data.hasOwnProperty('permission')) {
                obj['permission'] = ApiClient.convertToType(data['permission'], 'String');
            }
        }
        return obj;
    }


}

/**
 * User permission level for the project.
 * @member {module:model/MembershipUpdate.PermissionEnum} permission
 */
MembershipUpdate.prototype['permission'] = undefined;





/**
 * Allowed values for the <code>permission</code> property.
 * @enum {String}
 * @readonly
 */
MembershipUpdate['PermissionEnum'] = {

    /**
     * value: "View Only"
     * @const
     */
    "View Only": "View Only",

    /**
     * value: "Can Edit"
     * @const
     */
    "Can Edit": "Can Edit",

    /**
     * value: "Can Transfer"
     * @const
     */
    "Can Transfer": "Can Transfer",

    /**
     * value: "Can Execute"
     * @const
     */
    "Can Execute": "Can Execute",

    /**
     * value: "Full Control"
     * @const
     */
    "Full Control": "Full Control"
};



export default MembershipUpdate;

