/**
 * Tator REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MembershipSpec model module.
 * @module model/MembershipSpec
 * @version v1
 */
class MembershipSpec {
    /**
     * Constructs a new <code>MembershipSpec</code>.
     * @alias module:model/MembershipSpec
     */
    constructor() { 
        
        MembershipSpec.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MembershipSpec</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MembershipSpec} obj Optional instance to populate.
     * @return {module:model/MembershipSpec} The populated <code>MembershipSpec</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MembershipSpec();

            if (data.hasOwnProperty('user')) {
                obj['user'] = ApiClient.convertToType(data['user'], 'Number');
            }
            if (data.hasOwnProperty('permission')) {
                obj['permission'] = ApiClient.convertToType(data['permission'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Unique integer identifying a user.
 * @member {Number} user
 */
MembershipSpec.prototype['user'] = undefined;

/**
 * User permission level for the project.
 * @member {module:model/MembershipSpec.PermissionEnum} permission
 */
MembershipSpec.prototype['permission'] = undefined;





/**
 * Allowed values for the <code>permission</code> property.
 * @enum {String}
 * @readonly
 */
MembershipSpec['PermissionEnum'] = {

    /**
     * value: "View Only"
     * @const
     */
    "View Only": "View Only",

    /**
     * value: "Can Edit"
     * @const
     */
    "Can Edit": "Can Edit",

    /**
     * value: "Can Transfer"
     * @const
     */
    "Can Transfer": "Can Transfer",

    /**
     * value: "Can Execute"
     * @const
     */
    "Can Execute": "Can Execute",

    /**
     * value: "Full Control"
     * @const
     */
    "Full Control": "Full Control"
};



export default MembershipSpec;

