/**
 * Tator REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The VersionSpec model module.
 * @module model/VersionSpec
 * @version v1
 */
class VersionSpec {
    /**
     * Constructs a new <code>VersionSpec</code>.
     * @alias module:model/VersionSpec
     * @param name {String} Name of the version.
     */
    constructor(name) { 
        
        VersionSpec.initialize(this, name);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name) { 
        obj['name'] = name;
    }

    /**
     * Constructs a <code>VersionSpec</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/VersionSpec} obj Optional instance to populate.
     * @return {module:model/VersionSpec} The populated <code>VersionSpec</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new VersionSpec();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('show_empty')) {
                obj['show_empty'] = ApiClient.convertToType(data['show_empty'], 'Boolean');
            }
            if (data.hasOwnProperty('bases')) {
                obj['bases'] = ApiClient.convertToType(data['bases'], ['Number']);
            }
        }
        return obj;
    }


}

/**
 * Name of the version.
 * @member {String} name
 */
VersionSpec.prototype['name'] = undefined;

/**
 * Description of the version.
 * @member {String} description
 * @default ''
 */
VersionSpec.prototype['description'] = '';

/**
 * Whether to show this version on media for which no annotations exist.
 * @member {Boolean} show_empty
 * @default true
 */
VersionSpec.prototype['show_empty'] = true;

/**
 * Array of other version IDs that are dependencies of this version.
 * @member {Array.<Number>} bases
 */
VersionSpec.prototype['bases'] = undefined;






export default VersionSpec;

