/**
 * Tator REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The VideoDefinition model module.
 * @module model/VideoDefinition
 * @version v1
 */
class VideoDefinition {
    /**
     * Constructs a new <code>VideoDefinition</code>.
     * @alias module:model/VideoDefinition
     * @param codec {String} Human readable codec.
     * @param resolution {Array.<Number>} Resolution of the video in pixels (height, width).
     */
    constructor(codec, resolution) { 
        
        VideoDefinition.initialize(this, codec, resolution);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, codec, resolution) { 
        obj['codec'] = codec;
        obj['resolution'] = resolution;
    }

    /**
     * Constructs a <code>VideoDefinition</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/VideoDefinition} obj Optional instance to populate.
     * @return {module:model/VideoDefinition} The populated <code>VideoDefinition</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new VideoDefinition();

            if (data.hasOwnProperty('path')) {
                obj['path'] = ApiClient.convertToType(data['path'], 'String');
            }
            if (data.hasOwnProperty('size')) {
                obj['size'] = ApiClient.convertToType(data['size'], 'Number');
            }
            if (data.hasOwnProperty('bit_rate')) {
                obj['bit_rate'] = ApiClient.convertToType(data['bit_rate'], 'Number');
            }
            if (data.hasOwnProperty('codec')) {
                obj['codec'] = ApiClient.convertToType(data['codec'], 'String');
            }
            if (data.hasOwnProperty('resolution')) {
                obj['resolution'] = ApiClient.convertToType(data['resolution'], ['Number']);
            }
            if (data.hasOwnProperty('segment_info')) {
                obj['segment_info'] = ApiClient.convertToType(data['segment_info'], 'String');
            }
            if (data.hasOwnProperty('host')) {
                obj['host'] = ApiClient.convertToType(data['host'], 'String');
            }
            if (data.hasOwnProperty('http_auth')) {
                obj['http_auth'] = ApiClient.convertToType(data['http_auth'], 'String');
            }
            if (data.hasOwnProperty('codec_mime')) {
                obj['codec_mime'] = ApiClient.convertToType(data['codec_mime'], 'String');
            }
            if (data.hasOwnProperty('codec_description')) {
                obj['codec_description'] = ApiClient.convertToType(data['codec_description'], 'String');
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
            if (data.hasOwnProperty('segments_url')) {
                obj['segments_url'] = ApiClient.convertToType(data['segments_url'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Relative URL to the file.
 * @member {String} path
 */
VideoDefinition.prototype['path'] = undefined;

/**
 * File size in bytes.
 * @member {Number} size
 */
VideoDefinition.prototype['size'] = undefined;

/**
 * Bit rate in bits per second
 * @member {Number} bit_rate
 */
VideoDefinition.prototype['bit_rate'] = undefined;

/**
 * Human readable codec.
 * @member {String} codec
 */
VideoDefinition.prototype['codec'] = undefined;

/**
 * Resolution of the video in pixels (height, width).
 * @member {Array.<Number>} resolution
 */
VideoDefinition.prototype['resolution'] = undefined;

/**
 * Path to json file containing segment info.
 * @member {String} segment_info
 */
VideoDefinition.prototype['segment_info'] = undefined;

/**
 * If supplied will use this instead of currently connected host, e.g. https://example.com
 * @member {String} host
 */
VideoDefinition.prototype['host'] = undefined;

/**
 * If specified will be used for HTTP authorization in request for media, i.e. \"bearer <token>\".
 * @member {String} http_auth
 */
VideoDefinition.prototype['http_auth'] = undefined;

/**
 * Example mime: \"video/mp4; codecs=\"avc1.64001e\"\". Only relevant for streaming files, will assume example above if not present.
 * @member {String} codec_mime
 */
VideoDefinition.prototype['codec_mime'] = undefined;

/**
 * Description other than codec.
 * @member {String} codec_description
 */
VideoDefinition.prototype['codec_description'] = undefined;

/**
 * Required when this object is used with the MoveVideo endpoint, this field is the upload URL of the video file. It is is used to determine the src path.
 * @member {String} url
 */
VideoDefinition.prototype['url'] = undefined;

/**
 * Required when this object is used with the MoveVideo endpoint, this field is the upload URL of the segments file. It is is used to determine the src path.
 * @member {String} segments_url
 */
VideoDefinition.prototype['segments_url'] = undefined;






export default VideoDefinition;

