/**
 * Tator REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AlgorithmSpec model module.
 * @module model/AlgorithmSpec
 * @version 0.0.1
 */
class AlgorithmSpec {
    /**
     * Constructs a new <code>AlgorithmSpec</code>.
     * Algorithm registration creation spec.
     * @alias module:model/AlgorithmSpec
     * @param name {String} Unique name of the algorithm workflow.
     * @param user {Number} Unique integer identifying the user registering the algorithm.
     * @param manifest {String} Server URL to argo manifest file (.yaml)
     * @param filesPerJob {Number} Number of media files to be submitted to each workflow.
     */
    constructor(name, user, manifest, filesPerJob) { 
        
        AlgorithmSpec.initialize(this, name, user, manifest, filesPerJob);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, user, manifest, filesPerJob) { 
        obj['name'] = name;
        obj['user'] = user;
        obj['manifest'] = manifest;
        obj['files_per_job'] = filesPerJob;
    }

    /**
     * Constructs a <code>AlgorithmSpec</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AlgorithmSpec} obj Optional instance to populate.
     * @return {module:model/AlgorithmSpec} The populated <code>AlgorithmSpec</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AlgorithmSpec();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('user')) {
                obj['user'] = ApiClient.convertToType(data['user'], 'Number');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('manifest')) {
                obj['manifest'] = ApiClient.convertToType(data['manifest'], 'String');
            }
            if (data.hasOwnProperty('cluster')) {
                obj['cluster'] = ApiClient.convertToType(data['cluster'], 'Number');
            }
            if (data.hasOwnProperty('files_per_job')) {
                obj['files_per_job'] = ApiClient.convertToType(data['files_per_job'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * Unique name of the algorithm workflow.
 * @member {String} name
 */
AlgorithmSpec.prototype['name'] = undefined;

/**
 * Unique integer identifying the user registering the algorithm.
 * @member {Number} user
 */
AlgorithmSpec.prototype['user'] = undefined;

/**
 * Description of the algorithm.
 * @member {String} description
 */
AlgorithmSpec.prototype['description'] = undefined;

/**
 * Server URL to argo manifest file (.yaml)
 * @member {String} manifest
 */
AlgorithmSpec.prototype['manifest'] = undefined;

/**
 * Unique integer identifying the job cluster.
 * @member {Number} cluster
 */
AlgorithmSpec.prototype['cluster'] = undefined;

/**
 * Number of media files to be submitted to each workflow.
 * @member {Number} files_per_job
 */
AlgorithmSpec.prototype['files_per_job'] = undefined;






export default AlgorithmSpec;

