/**
 * Tator REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import EncodeConfig from './EncodeConfig';
import S3StorageConfig from './S3StorageConfig';

/**
 * The ArchiveConfig model module.
 * @module model/ArchiveConfig
 * @version 0.0.1
 */
class ArchiveConfig {
    /**
     * Constructs a new <code>ArchiveConfig</code>.
     * Settings for archival video encode and storage. If not set, the raw video will be stored in Tator.
     * @alias module:model/ArchiveConfig
     */
    constructor() { 
        
        ArchiveConfig.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ArchiveConfig</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ArchiveConfig} obj Optional instance to populate.
     * @return {module:model/ArchiveConfig} The populated <code>ArchiveConfig</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ArchiveConfig();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('encode')) {
                obj['encode'] = EncodeConfig.constructFromObject(data['encode']);
            }
            if (data.hasOwnProperty('s3_storage')) {
                obj['s3_storage'] = S3StorageConfig.constructFromObject(data['s3_storage']);
            }
        }
        return obj;
    }


}

/**
 * Name of this archive config, used for retrieval in case of multiple archive configs.
 * @member {String} name
 */
ArchiveConfig.prototype['name'] = undefined;

/**
 * @member {module:model/EncodeConfig} encode
 */
ArchiveConfig.prototype['encode'] = undefined;

/**
 * @member {module:model/S3StorageConfig} s3_storage
 */
ArchiveConfig.prototype['s3_storage'] = undefined;






export default ArchiveConfig;

