/**
 * Tator REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The FavoriteSpec model module.
 * @module model/FavoriteSpec
 * @version 0.0.1
 */
class FavoriteSpec {
    /**
     * Constructs a new <code>FavoriteSpec</code>.
     * @alias module:model/FavoriteSpec
     */
    constructor() { 
        
        FavoriteSpec.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>FavoriteSpec</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/FavoriteSpec} obj Optional instance to populate.
     * @return {module:model/FavoriteSpec} The populated <code>FavoriteSpec</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FavoriteSpec();

            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('values')) {
                obj['values'] = ApiClient.convertToType(data['values'], {'String': Object});
            }
            if (data.hasOwnProperty('page')) {
                obj['page'] = ApiClient.convertToType(data['page'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * Unique integer identifying a localization type.
 * @member {Number} type
 */
FavoriteSpec.prototype['type'] = undefined;

/**
 * Name of the favorite.
 * @member {String} name
 */
FavoriteSpec.prototype['name'] = undefined;

/**
 * Attribute name/value pairs.
 * @member {Object.<String, Object>} values
 */
FavoriteSpec.prototype['values'] = undefined;

/**
 * Integer specifying page to display on. Should be 1-10.
 * @member {Number} page
 * @default 1
 */
FavoriteSpec.prototype['page'] = 1;






export default FavoriteSpec;

