/**
 * Tator REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AttributeType from './AttributeType';
import ColorMap from './ColorMap';

/**
 * The LocalizationType model module.
 * @module model/LocalizationType
 * @version 0.0.1
 */
class LocalizationType {
    /**
     * Constructs a new <code>LocalizationType</code>.
     * Localization type.
     * @alias module:model/LocalizationType
     */
    constructor() { 
        
        LocalizationType.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>LocalizationType</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LocalizationType} obj Optional instance to populate.
     * @return {module:model/LocalizationType} The populated <code>LocalizationType</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LocalizationType();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('project')) {
                obj['project'] = ApiClient.convertToType(data['project'], 'Number');
            }
            if (data.hasOwnProperty('media')) {
                obj['media'] = ApiClient.convertToType(data['media'], ['Number']);
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('dtype')) {
                obj['dtype'] = ApiClient.convertToType(data['dtype'], 'String');
            }
            if (data.hasOwnProperty('colorMap')) {
                obj['colorMap'] = ColorMap.constructFromObject(data['colorMap']);
            }
            if (data.hasOwnProperty('line_width')) {
                obj['line_width'] = ApiClient.convertToType(data['line_width'], 'Number');
            }
            if (data.hasOwnProperty('visible')) {
                obj['visible'] = ApiClient.convertToType(data['visible'], 'Boolean');
            }
            if (data.hasOwnProperty('grouping_default')) {
                obj['grouping_default'] = ApiClient.convertToType(data['grouping_default'], 'Boolean');
            }
            if (data.hasOwnProperty('attribute_types')) {
                obj['attribute_types'] = ApiClient.convertToType(data['attribute_types'], [AttributeType]);
            }
        }
        return obj;
    }


}

/**
 * Unique integer identifying a localization type.
 * @member {Number} id
 */
LocalizationType.prototype['id'] = undefined;

/**
 * Unique integer identifying project for this leaf type.
 * @member {Number} project
 */
LocalizationType.prototype['project'] = undefined;

/**
 * List of integers identifying media types that this localization type may apply to.
 * @member {Array.<Number>} media
 */
LocalizationType.prototype['media'] = undefined;

/**
 * Name of the localization type.
 * @member {String} name
 */
LocalizationType.prototype['name'] = undefined;

/**
 * Description of the localization type.
 * @member {String} description
 */
LocalizationType.prototype['description'] = undefined;

/**
 * Shape of this localization type.
 * @member {module:model/LocalizationType.DtypeEnum} dtype
 */
LocalizationType.prototype['dtype'] = undefined;

/**
 * @member {module:model/ColorMap} colorMap
 */
LocalizationType.prototype['colorMap'] = undefined;

/**
 * Width of the line used to draw the localization.
 * @member {Number} line_width
 */
LocalizationType.prototype['line_width'] = undefined;

/**
 * Whether this type should be displayed in the UI.
 * @member {Boolean} visible
 * @default true
 */
LocalizationType.prototype['visible'] = true;

/**
 * Whether to group elements in the UI by default.
 * @member {Boolean} grouping_default
 * @default true
 */
LocalizationType.prototype['grouping_default'] = true;

/**
 * Attribute type definitions.
 * @member {Array.<module:model/AttributeType>} attribute_types
 */
LocalizationType.prototype['attribute_types'] = undefined;





/**
 * Allowed values for the <code>dtype</code> property.
 * @enum {String}
 * @readonly
 */
LocalizationType['DtypeEnum'] = {

    /**
     * value: "box"
     * @const
     */
    "box": "box",

    /**
     * value: "line"
     * @const
     */
    "line": "line",

    /**
     * value: "dot"
     * @const
     */
    "dot": "dot"
};



export default LocalizationType;

