/**
 * Tator REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AttributeValue from './AttributeValue';
import MediaFiles from './MediaFiles';

/**
 * The MediaUpdate model module.
 * @module model/MediaUpdate
 * @version 0.0.1
 */
class MediaUpdate {
    /**
     * Constructs a new <code>MediaUpdate</code>.
     * @alias module:model/MediaUpdate
     */
    constructor() { 
        
        MediaUpdate.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MediaUpdate</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MediaUpdate} obj Optional instance to populate.
     * @return {module:model/MediaUpdate} The populated <code>MediaUpdate</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MediaUpdate();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('media_files')) {
                obj['media_files'] = MediaFiles.constructFromObject(data['media_files']);
            }
            if (data.hasOwnProperty('last_edit_start')) {
                obj['last_edit_start'] = ApiClient.convertToType(data['last_edit_start'], 'Date');
            }
            if (data.hasOwnProperty('last_edit_end')) {
                obj['last_edit_end'] = ApiClient.convertToType(data['last_edit_end'], 'Date');
            }
            if (data.hasOwnProperty('attributes')) {
                obj['attributes'] = ApiClient.convertToType(data['attributes'], {'String': AttributeValue});
            }
            if (data.hasOwnProperty('thumbnail_url')) {
                obj['thumbnail_url'] = ApiClient.convertToType(data['thumbnail_url'], 'String');
            }
            if (data.hasOwnProperty('thumbnail_gif_url')) {
                obj['thumbnail_gif_url'] = ApiClient.convertToType(data['thumbnail_gif_url'], 'String');
            }
            if (data.hasOwnProperty('num_frames')) {
                obj['num_frames'] = ApiClient.convertToType(data['num_frames'], 'Number');
            }
            if (data.hasOwnProperty('fps')) {
                obj['fps'] = ApiClient.convertToType(data['fps'], 'Number');
            }
            if (data.hasOwnProperty('codec')) {
                obj['codec'] = ApiClient.convertToType(data['codec'], 'String');
            }
            if (data.hasOwnProperty('width')) {
                obj['width'] = ApiClient.convertToType(data['width'], 'Number');
            }
            if (data.hasOwnProperty('height')) {
                obj['height'] = ApiClient.convertToType(data['height'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * Name of the media.
 * @member {String} name
 */
MediaUpdate.prototype['name'] = undefined;

/**
 * @member {module:model/MediaFiles} media_files
 */
MediaUpdate.prototype['media_files'] = undefined;

/**
 * Datetime of the start of the session when this media or its annotations were last edited.
 * @member {Date} last_edit_start
 */
MediaUpdate.prototype['last_edit_start'] = undefined;

/**
 * Datetime of the end of the session when this media or its annotations were last edited.
 * @member {Date} last_edit_end
 */
MediaUpdate.prototype['last_edit_end'] = undefined;

/**
 * Object containing attribute values.
 * @member {Object.<String, module:model/AttributeValue>} attributes
 */
MediaUpdate.prototype['attributes'] = undefined;

/**
 * Upload URL for the thumbnail.
 * @member {String} thumbnail_url
 */
MediaUpdate.prototype['thumbnail_url'] = undefined;

/**
 * Upload URL for the thumbnail gif.
 * @member {String} thumbnail_gif_url
 */
MediaUpdate.prototype['thumbnail_gif_url'] = undefined;

/**
 * Number of frames in the video.
 * @member {Number} num_frames
 */
MediaUpdate.prototype['num_frames'] = undefined;

/**
 * Frame rate of the video.
 * @member {Number} fps
 */
MediaUpdate.prototype['fps'] = undefined;

/**
 * Codec of the original video.
 * @member {String} codec
 */
MediaUpdate.prototype['codec'] = undefined;

/**
 * Pixel width of the video.
 * @member {Number} width
 */
MediaUpdate.prototype['width'] = undefined;

/**
 * Pixel height of the video.
 * @member {Number} height
 */
MediaUpdate.prototype['height'] = undefined;






export default MediaUpdate;

