/**
 * Tator REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ArchiveConfig from './ArchiveConfig';
import ResolutionConfig from './ResolutionConfig';

/**
 * The MediaTypeUpdate model module.
 * @module model/MediaTypeUpdate
 * @version 0.0.1
 */
class MediaTypeUpdate {
    /**
     * Constructs a new <code>MediaTypeUpdate</code>.
     * @alias module:model/MediaTypeUpdate
     */
    constructor() { 
        
        MediaTypeUpdate.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MediaTypeUpdate</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MediaTypeUpdate} obj Optional instance to populate.
     * @return {module:model/MediaTypeUpdate} The populated <code>MediaTypeUpdate</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MediaTypeUpdate();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('file_format')) {
                obj['file_format'] = ApiClient.convertToType(data['file_format'], 'String');
            }
            if (data.hasOwnProperty('keep_original')) {
                obj['keep_original'] = ApiClient.convertToType(data['keep_original'], 'Boolean');
            }
            if (data.hasOwnProperty('archive_config')) {
                obj['archive_config'] = ApiClient.convertToType(data['archive_config'], [ArchiveConfig]);
            }
            if (data.hasOwnProperty('streaming_config')) {
                obj['streaming_config'] = ApiClient.convertToType(data['streaming_config'], [ResolutionConfig]);
            }
        }
        return obj;
    }


}

/**
 * Name of the media type.
 * @member {String} name
 */
MediaTypeUpdate.prototype['name'] = undefined;

/**
 * Description of the media type.
 * @member {String} description
 * @default ''
 */
MediaTypeUpdate.prototype['description'] = '';

/**
 * File extension. If omitted, any recognized file extension for the given dtype is accepted for upload. Do not include a dot prefix.
 * @member {String} file_format
 */
MediaTypeUpdate.prototype['file_format'] = undefined;

/**
 * For video dtype, whether to keep the original video file for archival purposes after transcoding. If true, the originally uploaded file will be available for download, otherwise downloads will use the transcoded videos.
 * @member {Boolean} keep_original
 * @default true
 */
MediaTypeUpdate.prototype['keep_original'] = true;

/**
 * Archive config definitions. If null, the raw file will be uploaded to Tator.
 * @member {Array.<module:model/ArchiveConfig>} archive_config
 */
MediaTypeUpdate.prototype['archive_config'] = undefined;

/**
 * Streaming config defintion. If null, the default will be used.
 * @member {Array.<module:model/ResolutionConfig>} streaming_config
 */
MediaTypeUpdate.prototype['streaming_config'] = undefined;






export default MediaTypeUpdate;

