/**
 * Tator REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ArchiveConfig from './ArchiveConfig';
import AttributeType from './AttributeType';
import ResolutionConfig from './ResolutionConfig';

/**
 * The MediaType model module.
 * @module model/MediaType
 * @version 0.0.1
 */
class MediaType {
    /**
     * Constructs a new <code>MediaType</code>.
     * Media type.
     * @alias module:model/MediaType
     */
    constructor() { 
        
        MediaType.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MediaType</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MediaType} obj Optional instance to populate.
     * @return {module:model/MediaType} The populated <code>MediaType</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MediaType();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('project')) {
                obj['project'] = ApiClient.convertToType(data['project'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('dtype')) {
                obj['dtype'] = ApiClient.convertToType(data['dtype'], 'String');
            }
            if (data.hasOwnProperty('file_format')) {
                obj['file_format'] = ApiClient.convertToType(data['file_format'], 'String');
            }
            if (data.hasOwnProperty('keep_original')) {
                obj['keep_original'] = ApiClient.convertToType(data['keep_original'], 'Boolean');
            }
            if (data.hasOwnProperty('default_volume')) {
                obj['default_volume'] = ApiClient.convertToType(data['default_volume'], 'Number');
            }
            if (data.hasOwnProperty('attribute_types')) {
                obj['attribute_types'] = ApiClient.convertToType(data['attribute_types'], [AttributeType]);
            }
            if (data.hasOwnProperty('archive_config')) {
                obj['archive_config'] = ApiClient.convertToType(data['archive_config'], [ArchiveConfig]);
            }
            if (data.hasOwnProperty('streaming_config')) {
                obj['streaming_config'] = ApiClient.convertToType(data['streaming_config'], [ResolutionConfig]);
            }
            if (data.hasOwnProperty('overlay_config')) {
                obj['overlay_config'] = ApiClient.convertToType(data['overlay_config'], {'String': Object});
            }
        }
        return obj;
    }


}

/**
 * Unique integer identifying a media type.
 * @member {Number} id
 */
MediaType.prototype['id'] = undefined;

/**
 * Unique integer identifying project for this media type.
 * @member {Number} project
 */
MediaType.prototype['project'] = undefined;

/**
 * Name of the media type.
 * @member {String} name
 */
MediaType.prototype['name'] = undefined;

/**
 * Description of the media type.
 * @member {String} description
 * @default ''
 */
MediaType.prototype['description'] = '';

/**
 * Type of the media, image or video.
 * @member {module:model/MediaType.DtypeEnum} dtype
 */
MediaType.prototype['dtype'] = undefined;

/**
 * File extension. If omitted, any recognized file extension for the given dtype is accepted for upload. Do not include a dot prefix.
 * @member {String} file_format
 */
MediaType.prototype['file_format'] = undefined;

/**
 * For video dtype, whether to keep the original video file for archival purposes after transcoding. If true, the originally uploaded file will be available for download, otherwise downloads will use the transcoded videos.
 * @member {Boolean} keep_original
 * @default true
 */
MediaType.prototype['keep_original'] = true;

/**
 * Default audio volume for this media type.
 * @member {Number} default_volume
 */
MediaType.prototype['default_volume'] = undefined;

/**
 * Attribute type definitions.
 * @member {Array.<module:model/AttributeType>} attribute_types
 */
MediaType.prototype['attribute_types'] = undefined;

/**
 * Archive config definitions. If null, the raw file will be uploaded to Tator.
 * @member {Array.<module:model/ArchiveConfig>} archive_config
 */
MediaType.prototype['archive_config'] = undefined;

/**
 * Streaming config defintion. If null, the default will be used.
 * @member {Array.<module:model/ResolutionConfig>} streaming_config
 */
MediaType.prototype['streaming_config'] = undefined;

/**
 * Overlay configuration
 * @member {Object.<String, Object>} overlay_config
 */
MediaType.prototype['overlay_config'] = undefined;





/**
 * Allowed values for the <code>dtype</code> property.
 * @enum {String}
 * @readonly
 */
MediaType['DtypeEnum'] = {

    /**
     * value: "image"
     * @const
     */
    "image": "image",

    /**
     * value: "video"
     * @const
     */
    "video": "video",

    /**
     * value: "multi"
     * @const
     */
    "multi": "multi"
};



export default MediaType;

