/**
 * Tator REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Project model module.
 * @module model/Project
 * @version 0.0.1
 */
class Project {
    /**
     * Constructs a new <code>Project</code>.
     * Project object.
     * @alias module:model/Project
     */
    constructor() { 
        
        Project.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Project</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Project} obj Optional instance to populate.
     * @return {module:model/Project} The populated <code>Project</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Project();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('summary')) {
                obj['summary'] = ApiClient.convertToType(data['summary'], 'String');
            }
            if (data.hasOwnProperty('thumb')) {
                obj['thumb'] = ApiClient.convertToType(data['thumb'], 'String');
            }
            if (data.hasOwnProperty('num_files')) {
                obj['num_files'] = ApiClient.convertToType(data['num_files'], 'Number');
            }
            if (data.hasOwnProperty('size')) {
                obj['size'] = ApiClient.convertToType(data['size'], 'Number');
            }
            if (data.hasOwnProperty('usernames')) {
                obj['usernames'] = ApiClient.convertToType(data['usernames'], ['String']);
            }
            if (data.hasOwnProperty('permission')) {
                obj['permission'] = ApiClient.convertToType(data['permission'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Unique integer identifying the project.
 * @member {Number} id
 */
Project.prototype['id'] = undefined;

/**
 * Name of the project.
 * @member {String} name
 */
Project.prototype['name'] = undefined;

/**
 * Summary of the project.
 * @member {String} summary
 * @default ''
 */
Project.prototype['summary'] = '';

/**
 * URL of thumbnail used to represent the project.
 * @member {String} thumb
 */
Project.prototype['thumb'] = undefined;

/**
 * Number of files in the project.
 * @member {Number} num_files
 */
Project.prototype['num_files'] = undefined;

/**
 * Size of the project in bytes.
 * @member {Number} size
 */
Project.prototype['size'] = undefined;

/**
 * List of usernames of project members.
 * @member {Array.<String>} usernames
 */
Project.prototype['usernames'] = undefined;

/**
 * Permission level of user making request.
 * @member {String} permission
 */
Project.prototype['permission'] = undefined;






export default Project;

