/**
 * Tator REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AttributeType from './AttributeType';

/**
 * The StateType model module.
 * @module model/StateType
 * @version 0.0.1
 */
class StateType {
    /**
     * Constructs a new <code>StateType</code>.
     * State type.
     * @alias module:model/StateType
     */
    constructor() { 
        
        StateType.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>StateType</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/StateType} obj Optional instance to populate.
     * @return {module:model/StateType} The populated <code>StateType</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new StateType();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('project')) {
                obj['project'] = ApiClient.convertToType(data['project'], 'Number');
            }
            if (data.hasOwnProperty('dtype')) {
                obj['dtype'] = ApiClient.convertToType(data['dtype'], 'String');
            }
            if (data.hasOwnProperty('media')) {
                obj['media'] = ApiClient.convertToType(data['media'], ['Number']);
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('association')) {
                obj['association'] = ApiClient.convertToType(data['association'], 'String');
            }
            if (data.hasOwnProperty('interpolation')) {
                obj['interpolation'] = ApiClient.convertToType(data['interpolation'], 'String');
            }
            if (data.hasOwnProperty('visible')) {
                obj['visible'] = ApiClient.convertToType(data['visible'], 'Boolean');
            }
            if (data.hasOwnProperty('grouping_default')) {
                obj['grouping_default'] = ApiClient.convertToType(data['grouping_default'], 'Boolean');
            }
            if (data.hasOwnProperty('attribute_types')) {
                obj['attribute_types'] = ApiClient.convertToType(data['attribute_types'], [AttributeType]);
            }
            if (data.hasOwnProperty('delete_child_localizations')) {
                obj['delete_child_localizations'] = ApiClient.convertToType(data['delete_child_localizations'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * Unique integer identifying a state type.
 * @member {Number} id
 */
StateType.prototype['id'] = undefined;

/**
 * Unique integer identifying project for this state type.
 * @member {Number} project
 */
StateType.prototype['project'] = undefined;

/**
 * String indicating data type. Always equal to \"state\".
 * @member {String} dtype
 */
StateType.prototype['dtype'] = undefined;

/**
 * List of integers identifying media types that this state type may apply to.
 * @member {Array.<Number>} media
 */
StateType.prototype['media'] = undefined;

/**
 * Name of the state type.
 * @member {String} name
 */
StateType.prototype['name'] = undefined;

/**
 * Description of the state type.
 * @member {String} description
 */
StateType.prototype['description'] = undefined;

/**
 * Type of object this state type is associated with.
 * @member {module:model/StateType.AssociationEnum} association
 */
StateType.prototype['association'] = undefined;

/**
 * Interpolation method used by the web interface.
 * @member {module:model/StateType.InterpolationEnum} interpolation
 * @default 'latest'
 */
StateType.prototype['interpolation'] = 'latest';

/**
 * Whether this state type should be displayed.
 * @member {Boolean} visible
 */
StateType.prototype['visible'] = undefined;

/**
 * Whether to group elements in the UI by default.
 * @member {Boolean} grouping_default
 * @default true
 */
StateType.prototype['grouping_default'] = true;

/**
 * Attribute type definitions.
 * @member {Array.<module:model/AttributeType>} attribute_types
 */
StateType.prototype['attribute_types'] = undefined;

/**
 * True if child localizations should be deleted when this state is deleted. Localizations will only be deleted if they are not associated with another state. 
 * @member {Boolean} delete_child_localizations
 * @default false
 */
StateType.prototype['delete_child_localizations'] = false;





/**
 * Allowed values for the <code>association</code> property.
 * @enum {String}
 * @readonly
 */
StateType['AssociationEnum'] = {

    /**
     * value: "Media"
     * @const
     */
    "Media": "Media",

    /**
     * value: "Frame"
     * @const
     */
    "Frame": "Frame",

    /**
     * value: "Localization"
     * @const
     */
    "Localization": "Localization"
};


/**
 * Allowed values for the <code>interpolation</code> property.
 * @enum {String}
 * @readonly
 */
StateType['InterpolationEnum'] = {

    /**
     * value: "none"
     * @const
     */
    "none": "none",

    /**
     * value: "latest"
     * @const
     */
    "latest": "latest",

    /**
     * value: "attr_style_range"
     * @const
     */
    "attr_style_range": "attr_style_range"
};



export default StateType;

