/**
 * Tator REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Transcode model module.
 * @module model/Transcode
 * @version 0.0.1
 */
class Transcode {
    /**
     * Constructs a new <code>Transcode</code>.
     * @alias module:model/Transcode
     */
    constructor() { 
        
        Transcode.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Transcode</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Transcode} obj Optional instance to populate.
     * @return {module:model/Transcode} The populated <code>Transcode</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Transcode();

            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('uid')) {
                obj['uid'] = ApiClient.convertToType(data['uid'], 'String');
            }
            if (data.hasOwnProperty('gid')) {
                obj['gid'] = ApiClient.convertToType(data['gid'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Message indicating transcode started successfully.
 * @member {String} message
 */
Transcode.prototype['message'] = undefined;

/**
 * UUID identifying the job.
 * @member {String} uid
 */
Transcode.prototype['uid'] = undefined;

/**
 * UUID identifying the job group.
 * @member {String} gid
 */
Transcode.prototype['gid'] = undefined;






export default Transcode;

