/**
 * Tator REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AttributeValue from './AttributeValue';

/**
 * The AttributeBulkUpdate model module.
 * @module model/AttributeBulkUpdate
 * @version v1
 */
class AttributeBulkUpdate {
    /**
     * Constructs a new <code>AttributeBulkUpdate</code>.
     * @alias module:model/AttributeBulkUpdate
     * @param attributes {Object.<String, module:model/AttributeValue>} Attribute values to bulk update an entity list.
     */
    constructor(attributes) { 
        
        AttributeBulkUpdate.initialize(this, attributes);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, attributes) { 
        obj['attributes'] = attributes;
    }

    /**
     * Constructs a <code>AttributeBulkUpdate</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AttributeBulkUpdate} obj Optional instance to populate.
     * @return {module:model/AttributeBulkUpdate} The populated <code>AttributeBulkUpdate</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AttributeBulkUpdate();

            if (data.hasOwnProperty('attributes')) {
                obj['attributes'] = ApiClient.convertToType(data['attributes'], {'String': AttributeValue});
            }
        }
        return obj;
    }


}

/**
 * Attribute values to bulk update an entity list.
 * @member {Object.<String, module:model/AttributeValue>} attributes
 */
AttributeBulkUpdate.prototype['attributes'] = undefined;






export default AttributeBulkUpdate;

