/**
 * Tator REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AttributeValue from './AttributeValue';
import AutocompleteService from './AutocompleteService';

/**
 * The AttributeType model module.
 * @module model/AttributeType
 * @version v1
 */
class AttributeType {
    /**
     * Constructs a new <code>AttributeType</code>.
     * @alias module:model/AttributeType
     */
    constructor() { 
        
        AttributeType.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AttributeType</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AttributeType} obj Optional instance to populate.
     * @return {module:model/AttributeType} The populated <code>AttributeType</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AttributeType();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('dtype')) {
                obj['dtype'] = ApiClient.convertToType(data['dtype'], 'String');
            }
            if (data.hasOwnProperty('required')) {
                obj['required'] = ApiClient.convertToType(data['required'], 'Boolean');
            }
            if (data.hasOwnProperty('order')) {
                obj['order'] = ApiClient.convertToType(data['order'], 'Number');
            }
            if (data.hasOwnProperty('default')) {
                obj['default'] = AttributeValue.constructFromObject(data['default']);
            }
            if (data.hasOwnProperty('minimum')) {
                obj['minimum'] = ApiClient.convertToType(data['minimum'], 'Number');
            }
            if (data.hasOwnProperty('maximum')) {
                obj['maximum'] = ApiClient.convertToType(data['maximum'], 'Number');
            }
            if (data.hasOwnProperty('choices')) {
                obj['choices'] = ApiClient.convertToType(data['choices'], ['String']);
            }
            if (data.hasOwnProperty('labels')) {
                obj['labels'] = ApiClient.convertToType(data['labels'], ['String']);
            }
            if (data.hasOwnProperty('autocomplete')) {
                obj['autocomplete'] = AutocompleteService.constructFromObject(data['autocomplete']);
            }
            if (data.hasOwnProperty('use_current')) {
                obj['use_current'] = ApiClient.convertToType(data['use_current'], 'Boolean');
            }
            if (data.hasOwnProperty('style')) {
                obj['style'] = ApiClient.convertToType(data['style'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Name of the attribute.
 * @member {String} name
 */
AttributeType.prototype['name'] = undefined;

/**
 * Description of the attribute.
 * @member {String} description
 * @default ''
 */
AttributeType.prototype['description'] = '';

/**
 * Data type of the attribute.
 * @member {module:model/AttributeType.DtypeEnum} dtype
 */
AttributeType.prototype['dtype'] = undefined;

/**
 * True if this attribute is required for POST requests.
 * @member {Boolean} required
 * @default false
 */
AttributeType.prototype['required'] = false;

/**
 * Integer specifying relative order this attribute is displayed in the UI. Negative values are hidden by default.
 * @member {Number} order
 * @default 0
 */
AttributeType.prototype['order'] = 0;

/**
 * @member {module:model/AttributeValue} default
 */
AttributeType.prototype['default'] = undefined;

/**
 * Lower bound for int or float dtype.
 * @member {Number} minimum
 */
AttributeType.prototype['minimum'] = undefined;

/**
 * Upper bound for int or float dtype.
 * @member {Number} maximum
 */
AttributeType.prototype['maximum'] = undefined;

/**
 * Array of possible values for enum dtype.
 * @member {Array.<String>} choices
 */
AttributeType.prototype['choices'] = undefined;

/**
 * Array of labels for enum dtype.
 * @member {Array.<String>} labels
 */
AttributeType.prototype['labels'] = undefined;

/**
 * @member {module:model/AutocompleteService} autocomplete
 */
AttributeType.prototype['autocomplete'] = undefined;

/**
 * True to use current datetime as default for datetime dtype.
 * @member {Boolean} use_current
 */
AttributeType.prototype['use_current'] = undefined;

/**
 * Available options: disabled|long_string|start_frame|end_frame|start_frame_check|end_frame_check   Multiple options can be chained together separated by white space. \"disabled\" will not allow the user to edit the attribute in the Tator GUI. Create a text area string if \"long_string\" is combined with \"string\" dtype. \"start_frame\" and \"end_frame\" used in conjunction with \"attr_style_range\" interpolation. \"start_frame_check and \"end_frame_check\" are used in conjunction with \"attr_style_range\" interpolation. When associated with a bool, these checks will result in Tator GUI changes with the corresponding start_frame and end_frame attributes.
 * @member {String} style
 */
AttributeType.prototype['style'] = undefined;





/**
 * Allowed values for the <code>dtype</code> property.
 * @enum {String}
 * @readonly
 */
AttributeType['DtypeEnum'] = {

    /**
     * value: "bool"
     * @const
     */
    "bool": "bool",

    /**
     * value: "int"
     * @const
     */
    "int": "int",

    /**
     * value: "float"
     * @const
     */
    "float": "float",

    /**
     * value: "enum"
     * @const
     */
    "enum": "enum",

    /**
     * value: "string"
     * @const
     */
    "string": "string",

    /**
     * value: "datetime"
     * @const
     */
    "datetime": "datetime",

    /**
     * value: "geopos"
     * @const
     */
    "geopos": "geopos"
};



export default AttributeType;

