/**
 * Tator REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MediaFiles from './MediaFiles';

/**
 * The MoveVideoSpec model module.
 * @module model/MoveVideoSpec
 * @version v1
 */
class MoveVideoSpec {
    /**
     * Constructs a new <code>MoveVideoSpec</code>.
     * @alias module:model/MoveVideoSpec
     * @param mediaFiles {module:model/MediaFiles} 
     */
    constructor(mediaFiles) { 
        
        MoveVideoSpec.initialize(this, mediaFiles);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, mediaFiles) { 
        obj['media_files'] = mediaFiles;
    }

    /**
     * Constructs a <code>MoveVideoSpec</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MoveVideoSpec} obj Optional instance to populate.
     * @return {module:model/MoveVideoSpec} The populated <code>MoveVideoSpec</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MoveVideoSpec();

            if (data.hasOwnProperty('media_files')) {
                obj['media_files'] = MediaFiles.constructFromObject(data['media_files']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/MediaFiles} media_files
 */
MoveVideoSpec.prototype['media_files'] = undefined;






export default MoveVideoSpec;

